# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41a766946ead9786b08d3b7f43890877d45719963c73d226d6f77f1471db0b360623dbf0615a7528c9f851164a3032444a971e81e678e61bf748ffd374571041

test:
  secret_key_base: 785d498f4146104dcf45786c5761827178c6b41720e0422f3699404dccdf17b5a8cc2156cfbeaa4ed80bb3e5c244eb59815d198ce3824a6333d2a3d88f42141f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
